services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: buildingsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5413:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  sse-emitter-be:
    build:
      context: ./sse-emitter-be
    ports:
      - "7182:7182"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/buildingsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CORS_ALLOWED_ORIGINS: http://localhost:4202

  sse-emitter-fe:
    build:
      context: ./sse-emitter-fe
    ports:
      - "4202:80"
    depends_on:
      - sse-emitter-be